[project]
name = "etabeta"
version = "0.0.1"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "openai",
    "mypy",
    "black",
    "flake8",
    "flake8-bugbear",
    "colorlog",
]

[tool.setuptools]
py-modules = []