[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "etabeta"
version = "0.0.1"
# dependencies are managed by Nix!

[tool.setuptools.packages.find]
where = ["."]
include = ["*"] 
namespaces = false